name: haproxy-collector # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Python tool for collecting, parsing, and storing data from HAProxy instances.
description: |
  The HAProxy Collector is a Python package designed to collect, parse, 
  and store configuration and runtime data from HAProxy instances. 
  It integrates with database systems and supports advanced HAProxy 
  features such as backend switching and ACLs. The collector maps domains to 
  backend server IPs, stores data in a database, and is modular and extensible for 
  advanced use cases.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  main:
    plugin: python
    source: git@github.com:ibrahim-dwellir/haproxy-collector.git
    source-type: git
    source-branch: master
  bin:
      plugin: dump
      source-type: git
      source: git@github.com:ibrahim-dwellir/haproxy-collector.git
      source-branch: master
      source-subdir: snap/bin
      override-build: |
        mkdir -p $SNAPCRAFT_PART_INSTALL/bin
        cp haproxy-collector $SNAPCRAFT_PART_INSTALL/bin/haproxy-collector
        chmod +x $SNAPCRAFT_PART_INSTALL/bin/haproxy-collector
apps:
  haproxy-collector:
    command: bin/haproxy-collector
    plugs:
      - network
      - network-bind
  timer:
    command: bin/haproxy-collector
    daemon: oneshot
    timer: "00:00-24:00/144" # Run every 10 minutes
    plugs:
      - network
      - network-bind
