name: build and publish snap
on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop
      - stage
  pull_request:
    branches:
      - master
      - develop
      - stage
jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: build-snap

    - run: |
        sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}
  publish:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{needs.build.outputs.snap-file}}
        release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
